### ISSUE TITLE
Random ClassCastException in DatePickerPopWin.java

### ISSUE THREAD

**Issue by eefret** [brucetoo/PickView#16]
I got this exception the other day while playing and turning the device while testing my application.

```
03-01 10:06:15.484 12478-12478/? E/Bebler$1[uncaughtException] - 152: java.lang.RuntimeException: Unable to resume activity
 {com.bebler.app/com.bebler.app.activity.Registration}: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.Button                                                                          at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3019)                                                                          
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3050)                                                                          
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2425)                                                                          
at android.app.ActivityThread.access$900(ActivityThread.java:154)                                                                          
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)                                                                          
at android.os.Handler.dispatchMessage(Handler.java:102)                                                                          
at android.os.Looper.loop(Looper.java:135)                                                                          
at android.app.ActivityThread.main(ActivityThread.java:5294)                                                                          
at java.lang.reflect.Method.invoke(Native Method)                                                                          
at java.lang.reflect.Method.invoke(Method.java:372)                                                                          
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)                                                                          
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)                                                                       
Caused by: java.lang.ClassCastException: android.widget.LinearLayout cannot be cast to android.widget.Button                                                                          
at com.bruce.pickerview.popwindow.DatePickerPopWin.initView(DatePickerPopWin.java:163)                                                                          
at com.bruce.pickerview.popwindow.DatePickerPopWin.<init>(DatePickerPopWin.java:154)                                                                          
at com.bruce.pickerview.popwindow.DatePickerPopWin$Builder.build(DatePickerPopWin.java:138)                                                                          
at com.bebler.app.activity.fragment.YourName.initialize(YourName.java:182)                                                                          
at com.bebler.app.activity.fragment.YourName.onCreateView(YourName.java:67)                                                                          
at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)                                                                          
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)                                                                          
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)                                                                          
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)                                                                          
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)                                                                          
at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)                                                                          
at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:452)                                                                          
at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:141)                                                                          
at android.app.Activity.performResume(Activity.java:6089)                                                                          
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3008)                                                                          
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3050)                                                                           
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2425)                                                                           
at android.app.ActivityThread.access$900(ActivityThread.java:154)                                                                           
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)                                                                           
at android.os.Handler.dispatchMessage(Handler.java:102)                                                                           
at android.os.Looper.loop(Looper.java:135)                                                                           
at android.app.ActivityThread.main(ActivityThread.java:5294)                                                                           
at java.lang.reflect.Method.invoke(Native Method)                                                                           
at java.lang.reflect.Method.invoke(Method.java:372)                                                                          
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)                                                                           
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

**Comment by brucetoo** [comment]
Rotate device ?

**Comment by eefret** [comment]
Yeah on Device Rotation, Althought it was very random and sincerely I have read the code to look for the reason and it doesnt make sense at all, maybe you're using a custom Button widget or something...

**Comment by brucetoo** [comment]
This may be the problem of recreate your activity or fragment when rotate device,try [setRetainInstance](http://developer.android.com/reference/android/app/Fragment.html#setRetainInstance(boolean))
